#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_LARVESTA,
    MUGSHOT_JIGGLYPUFF,
    MUGSHOT_PHANPY,
    MUGSHOT_BAGON,
    MUGSHOT_DRAMPA,
    MUGSHOT_ARCHEN,
    MUGSHOT_TYRANTRUM,
    MUGSHOT_RAMPARDOS,
    MUGSHOT_CRADILY,
    MUGSHOT_KABUTO,
    MUGSHOT_COUNT,
};

enum MugshotEmotes {
    MUGSHOT_EMOTE_NORMAL,
    MUGSHOT_EMOTE_ANGRY,
    MUGSHOT_EMOTE_CRYING,
    MUGSHOT_EMOTE_DETERMINED,
    MUGSHOT_EMOTE_DIZZY,
    MUGSHOT_EMOTE_HAPPY,
    MUGSHOT_EMOTE_INSPIRED,
    MUGSHOT_EMOTE_JOYOUS,
    MUGSHOT_EMOTE_PAIN,
    MUGSHOT_EMOTE_SAD,
    MUGSHOT_EMOTE_SHOUTING,
    MUGSHOT_EMOTE_SIGH,
    MUGSHOT_EMOTE_STUNNED,
    MUGSHOT_EMOTE_SURPRISED,
    MUGSHOT_EMOTE_TEARY_EYED,
    MUGSHOT_EMOTE_WORRIED,
    MUGSHOT_EMOTE_SPECIAL,
    MUGSHOT_EMOTE_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
