JurassicPark_Black_Cutscene_MapScripts::
# 3 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, JurassicPark_Black_Cutscene_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE
	.byte 0

JurassicPark_Black_Cutscene_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE:
# 5 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	map_script_2 VAR_INTRO_BOAT_CUTSCENE, 0, Black_Cutscene_Boat_Intro
	.2byte 0


Black_Cutscene_Boat_Intro::
# 11 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	lockall
# 12 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	playse SE_THUNDERSTORM
# 13 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	delay 20
# 14 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_0
# 15 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	closemessage
# 16 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	playse SE_THUNDER
# 17 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	waitse
# 18 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	delay 5
# 19 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	playse SE_THUNDER2
# 20 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	waitse
# 22 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_1
# 23 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	playse SE_THUNDER
# 25 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_2
# 27 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_3
# 29 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_4
# 31 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_5
# 33 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_6
# 34 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	closemessage
# 35 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	delay 10
# 36 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	playse SE_THUNDER2
# 37 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	waitse
# 38 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	delay 10
# 40 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_7
# 42 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_8
# 44 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_9
# 46 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_10
# 48 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_11
# 50 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_12
# 51 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	closemessage
# 52 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	delay 10
# 53 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	playse SE_THUNDER
# 54 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	waitse
# 55 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	delay 10
# 57 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_13
# 59 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_14
# 61 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_15
# 63 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_16
# 65 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_17
# 67 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_18
# 69 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_19
# 71 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_20
# 73 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	msgbox Black_Cutscene_Boat_Intro_Text_21
# 74 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	closemessage
# 75 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	delay 5
# 76 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	playse SE_THUNDER2
# 77 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	waitse
# 78 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	delay 5
# 79 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	playse SE_M_HYDRO_PUMP
# 80 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	waitse
# 81 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	playse SE_M_EXPLOSION
# 82 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	waitse
# 83 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	delay 30
# 84 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	setvar VAR_INTRO_BOAT_CUTSCENE, 1
# 85 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	warpsilent MAP_JURASSIC_PARK_BEACH_DOCKS, 0
	return


Black_Cutscene_Boat_Intro_Text_0:
# 14 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "Somewhere, in the deep ocean…$"

Black_Cutscene_Boat_Intro_Text_1:
# 22 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "A-are you okay, everyone?!$"

Black_Cutscene_Boat_Intro_Text_2:
# 25 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "(Urgh…\n"
	.string "I think I'm going to be sick…)$"

Black_Cutscene_Boat_Intro_Text_3:
# 27 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "You and your treasure maps!\p"
	.string "There was supposed to be land, here!\n"
	.string "Land!$"

Black_Cutscene_Boat_Intro_Text_4:
# 29 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "W-we just got a little off course, is\n"
	.string "all!$"

Black_Cutscene_Boat_Intro_Text_5:
# 31 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "A little off course.$"

Black_Cutscene_Boat_Intro_Text_6:
# 33 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "(Here we go again…)$"

Black_Cutscene_Boat_Intro_Text_7:
# 40 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "Erm, guys…?$"

Black_Cutscene_Boat_Intro_Text_8:
# 42 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "I'm sure we'll find the island!\p"
	.string "We have to be very close, now!$"

Black_Cutscene_Boat_Intro_Text_9:
# 44 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "If we don't get thrown overboard first,\n"
	.string "that is!$"

Black_Cutscene_Boat_Intro_Text_10:
# 46 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "GUYS!\p"
	.string "Look, over there!\n"
	.string "Isn't that…?$"

Black_Cutscene_Boat_Intro_Text_11:
# 48 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "Look at w-$"

Black_Cutscene_Boat_Intro_Text_12:
# 50 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "Oh.\n"
	.string "Oh, no.$"

Black_Cutscene_Boat_Intro_Text_13:
# 57 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "(That wave…\n"
	.string "It's awfully big, isn't it…?)$"

Black_Cutscene_Boat_Intro_Text_14:
# 59 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "Turn the ship around!\n"
	.string "NOW!\p"
	.string "We have to face it dead on!$"

Black_Cutscene_Boat_Intro_Text_15:
# 61 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "On it!$"

Black_Cutscene_Boat_Intro_Text_16:
# 63 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "We're gonna die!\n"
	.string "We're gonna die!$"

Black_Cutscene_Boat_Intro_Text_17:
# 65 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "We're not gonna die if you just GIVE US\n"
	.string "A HAND!$"

Black_Cutscene_Boat_Intro_Text_18:
# 67 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "(No! It's too late!\n"
	.string "It's already here!)$"

Black_Cutscene_Boat_Intro_Text_19:
# 69 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "Everyone!\n"
	.string "Brace for impact!$"

Black_Cutscene_Boat_Intro_Text_20:
# 71 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "A{PAUSE 10}h{PAUSE 10}h{PAUSE 10}h{PAUSE 10}h{PAUSE 10}h{PAUSE 10}!$"

Black_Cutscene_Boat_Intro_Text_21:
# 73 "data/maps/JurassicPark_Black_Cutscene/scripts.pory"
	.string "N{PAUSE 10}o{PAUSE 10}o{PAUSE 10}o{PAUSE 10}o{PAUSE 10}o{PAUSE 10}!$"
